### ISSUE TITLE
Нет описания какия сторонние либы используются и как их поставить.

### ISSUE THREAD

**Issue by avlechen** [gwyrwch/travelling-salesman#3]

**Comment by gwyrwch** [comment]
добавила там  ссылку на репозиторий. 
продублирую здесь :
https://github.com/jarro2783/cxxopts

Эта библиотека использовалась для того, чтобы парсить параметры командной строки.

**Comment by gwyrwch** [comment]
Теперь еще используются несколько других.

Как установить на мак:

1. Устанавливаем `brew install boost`, `brew install boost-python`. Смотрим куда установился (в моем случае `/usr/local/Cellar/boost/1.71.0`. Второй нужен, т.к. boost/python кроме хедеров содержит и файлы, которые необходимо компилировать заранее.
~~~CMake
set(Boost_INCLUDE_DIR /usr/local/Cellar/boost/1.71.0/include)
set(Boost_LIBRARY_DIR /usr/local/Cellar/boost/1.71.0/lib)
find_package(Boost COMPONENTS system filesystem python37 numpy37 REQUIRED)

target_link_libraries(<executable> ${Boost_LIBRARIES})
~~~

2. Устанавливаем GTK+ `brew install gtkmm3`, а так же `brew install pygobject3`:
~~~CMake

find_package(PkgConfig)
pkg_check_modules(GTKMM gtkmm-3.0)

link_directories(${GTKMM_LIBRARY_DIRS})
include_directories(include ${GTKMM_INCLUDE_DIRS})

pkg_check_modules(PYGOBJECT pygobject-3.0)

link_directories(${PYGOBJECT_LIBRARY_DIRS})
include_directories(include ${PYGOBJECT_INCLUDE_DIRS})

target_link_libraries(<executable> ${GTKMM_LIBRARIES} ${PYGOBJECT_LIBRARIES})
~~~

3. Проверяем, что установлен `python`. Линкуем `PythonLibs`:
~~~CMake
find_package(PythonLibs REQUIRED)
include_directories(${PYTHON_INCLUDE_DIRS})

target_link_libraries(<executable>  ${PYTHON_LIBRARIES})
~~~

4. `pip3 install cairocffi, pgi`.
